# Generated by Django 3.2.5 on 2021-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('RegNo', models.CharField(max_length=8)),
                ('Year', models.DecimalField(decimal_places=0, max_digits=1)),
                ('DateOfBirth', models.DateField()),
                ('Department', models.CharField(max_length=50)),
                ('MobileNumber', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
