# Generated by Django 3.2.5 on 2021-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='AreaOfInterest',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
