# Generated by Django 3.2.5 on 2021-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0002_join_areaofinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='AreaOfInterest',
            field=models.CharField(default='True', max_length=100),
        ),
    ]
